services:
  db:
    image: postgres:13
    restart: always
    container_name: notes_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "3000:3000"
    container_name: notes_api
    environment:
      PORT: ${PORT:- 3000}
      DB_CLIENT: ${DB_CLIENT:- pg}
      DB_USER: ${DB_USER}
      DB_HOST: db # service
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT:- 5432}
    depends_on:
      - db

volumes:
  pgdata:
